// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZyiAEjKmKQFVbY__R7snWG4PAOA3CRZw',
    appId: '1:393579161746:web:6bfaa2c8a1830fd5449e4b',
    messagingSenderId: '393579161746',
    projectId: 'edaproject-81b6b',
    authDomain: 'edaproject-81b6b.firebaseapp.com',
    storageBucket: 'edaproject-81b6b.firebasestorage.app',
    measurementId: 'G-QJMPZ4LK8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtzT7E_3cRoEO9KhLPxTkIN-a3m7YXlzc',
    appId: '1:393579161746:android:f2cc480410980d9e449e4b',
    messagingSenderId: '393579161746',
    projectId: 'edaproject-81b6b',
    storageBucket: 'edaproject-81b6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRrv7waYox3jG2XmN6iSsrPHENl2SHnY4',
    appId: '1:393579161746:ios:a4975e94d6cc3c6e449e4b',
    messagingSenderId: '393579161746',
    projectId: 'edaproject-81b6b',
    storageBucket: 'edaproject-81b6b.firebasestorage.app',
    iosBundleId: 'com.example.simpleexpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRrv7waYox3jG2XmN6iSsrPHENl2SHnY4',
    appId: '1:393579161746:ios:a4975e94d6cc3c6e449e4b',
    messagingSenderId: '393579161746',
    projectId: 'edaproject-81b6b',
    storageBucket: 'edaproject-81b6b.firebasestorage.app',
    iosBundleId: 'com.example.simpleexpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZyiAEjKmKQFVbY__R7snWG4PAOA3CRZw',
    appId: '1:393579161746:web:ce632f8fcefb0747449e4b',
    messagingSenderId: '393579161746',
    projectId: 'edaproject-81b6b',
    authDomain: 'edaproject-81b6b.firebaseapp.com',
    storageBucket: 'edaproject-81b6b.firebasestorage.app',
    measurementId: 'G-5YVQQ6C1X6',
  );
}
